services:
  # FastAPI Application Service
  api:
    build: ./api
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    ports:
      - "5001:5000"
    environment:
      # Use the service name for the Prefect API URL
      - PREFECT_API_URL=http://prefect-server:4200/api
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - FLOW_RUN_TIMEOUT=180
    depends_on:
      prefect-server:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  # PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO Object Storage Service
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Prefect Server
  prefect-server:
    build: ./prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      # --- FIX: Simplify to the correct environment variables ---
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:4200/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 10

  # Prefect Worker Service
  prefect-worker:
    build: ./prefect-worker
    command: sh -c "python worker.py && prefect worker start --pool default"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      prefect-server:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared

  # Streamlit UI Service
  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:5000
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./streamlit_app:/app

volumes:
  postgres_data:
  minio_data:
  prefect_data: